<?php
/**
 * @file
 * Code for the Print Count Stats feature.
 */

include_once 'print_count_stats.features.inc';

/**
 * Implements hook_menu().
 */
function print_count_stats_menu() {
  $items = array();
  $items['print_count_stats'] = array(
    'title' => 'Print Count Stats',
    'page callback' => '_print_count_stats_page',
    'access callback' => '_access_print_count_stats',
    'expanded' => TRUE
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function print_count_stats_permission() {
  return array(
    'view print count stats' => array(
      'title' => t('View Print Count Stats')
    )
  );
}

/**
 * Access callback for permission to view print count stats.
 */
function _access_print_count_stats() {
  return user_access('view print count stats');
}

/**
 * Custom page callback function
 */
function _print_count_stats_page() {
  $output = '<p>Test</p>';
  return $output;
}