<?php
/**
 * @file
 * Code for the Print Count Stats feature.
 */

include_once 'print_count_stats.features.inc';

/**
 * Implements hook_menu().
 */
function print_count_stats_menu() {
  $items = array();
  $items['print_count_stats'] = array(
    'title' => 'Print Count Stats',
    'page callback' => '_print_count_stats_page',
    'access callback' => '_access_print_count_stats',
    'expanded' => TRUE
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function print_count_stats_permission() {
  return array(
    'view print count stats' => array(
      'title' => t('View Print Count Stats')
    )
  );
}

/**
 * Access callback for permission to view print count stats.
 */
function _access_print_count_stats() {
  return user_access('view print count stats');
}

/**
 * Custom page callback function
 */
function _print_count_stats_page() {
  $nodes = node_load_multiple(array(), array('type' => 'library_printer'));
  $rows  = array();
  $months = array();

  foreach( $nodes as $node ) {
  	$lib_id = field_get_items('node', $node, 'field_library');
  	$lib = field_view_value( 'node', $node, 'field_library', $lib_id[0]);
  	$totals = array();
  	$diffs  = array();
  	$prev   = 0;
  	$results = db_query('SELECT * FROM {print_count_stats_counter} WHERE nid = :nid ORDER BY year, month', array(':nid' => $node->nid));
  	foreach( $results as $result ) {
  		$months[ $result->year . '-' . $result->month ] = 1;
  		$count = $result->counter;

  		$totals[] = $count;
  		$diffs[] = $count - $prev;
  		$prev = $count;
  	}
   	$rows[] = array( 'data' => array_merge( array( array( 'data' => $node->title . '<br/><i style="font-weight:normal;">' . $lib['#title'] . '</i>', 'rowspan' => 2, 'header' => 1), 'Total' ), $totals ));
  	$rows[] = array( 'data' => array_merge( array( 'Diff' ), $diffs ));
  }
  $output = theme('table', array( 'header' => array_merge( array(t('Printer'), '' ), array_keys($months)), 'rows' => $rows ));
  return $output;
}